### ISSUE TITLE
Windows Phone 8 - не работает авторизация

### ISSUE THREAD

**Issue by daynoter** [daynoter/daynoter.com#6]

**Comment by gormxm** [comment]
Скриншоты процесса
![wp_ss_20151002_0001](https://cloud.githubusercontent.com/assets/14939761/10245740/3aae01a8-6913-11e5-8709-d6d87b71e47e.jpg)
![wp_ss_20151002_0002](https://cloud.githubusercontent.com/assets/14939761/10245743/3ac61d38-6913-11e5-89ac-6c64737b236a.jpg)
![wp_ss_20151002_0003](https://cloud.githubusercontent.com/assets/14939761/10245744/3ad402cc-6913-11e5-91f4-265a66d46446.jpg)

**Comment by gormxm** [comment]
https://app.daynoter.com/_oauth/google?state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJMREU4WEI4YzVtSXliVmxuVnZBM2plWGdOV09Wb1VOUXJtd05VNGpTTzZ6IiwiaXNDb3Jkb3ZhIjpmYWxzZX0%3D&code=4/BJ2pCDP5__wmvtqRGIryI78kYOKe_6ICGzWcAKCB5ks#

**Comment by gormxm** [comment]
ссылка на экране (click here) соответствует ссылке которая в браузере уже отрыта
